// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY2K1vJMDuJlbvC1WpMB5SsVhcQjdPMtw',
    appId: '1:862200294798:web:aa040340f61ce435fa88df',
    messagingSenderId: '862200294798',
    projectId: 'sumut-adventure',
    authDomain: 'sumut-adventure.firebaseapp.com',
    storageBucket: 'sumut-adventure.appspot.com',
    measurementId: 'G-XYM90DDLPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLNCrmTRiZND0Px4Xe-UP6V-pt0QD40FY',
    appId: '1:862200294798:android:8648ad63309e2d09fa88df',
    messagingSenderId: '862200294798',
    projectId: 'sumut-adventure',
    storageBucket: 'sumut-adventure.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGVxYd-0mgk50ZOW_EoYF1wZaDgZM2jtA',
    appId: '1:862200294798:ios:2b46431061ca5044fa88df',
    messagingSenderId: '862200294798',
    projectId: 'sumut-adventure',
    storageBucket: 'sumut-adventure.appspot.com',
    iosBundleId: 'com.example.assessment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGVxYd-0mgk50ZOW_EoYF1wZaDgZM2jtA',
    appId: '1:862200294798:ios:2b46431061ca5044fa88df',
    messagingSenderId: '862200294798',
    projectId: 'sumut-adventure',
    storageBucket: 'sumut-adventure.appspot.com',
    iosBundleId: 'com.example.assessment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY2K1vJMDuJlbvC1WpMB5SsVhcQjdPMtw',
    appId: '1:862200294798:web:9c93efcee36952aafa88df',
    messagingSenderId: '862200294798',
    projectId: 'sumut-adventure',
    authDomain: 'sumut-adventure.firebaseapp.com',
    storageBucket: 'sumut-adventure.appspot.com',
    measurementId: 'G-H8VLYHYF1B',
  );
}
